added administrator permission to admin roles
nwplus/Factotum pull request #239
Opened 2021-08-06 05:58 UTC by samanthatuhseng

# TL;DR

# Description
Added if statement to check if role is admin during init-bot when it tries to create the role to give it administrator permissions. Closes #227 .

## Why
It was a bug
## User Changes

## Tests Done
manually tested on discord test server 3: ran init-bot and bot made a bunch of roles then checked if each role had appropriate permissions.
# Breaking Changes

2021-08-06 06:02 UTC, mwang2000 approved these changes

2021-08-07 06:56 UTC, meleongg reviewed
good job very cool if else expression

2021-08-07 06:57 UTC, meleongg approved these changes

2021-08-09 18:42 UTC, JPGarCar requested changes

2021-09-20 16:29 UTC, JPGarCar approved these changes
Will merge to get things going!

2021-09-20 16:29 UTC, merged